tabs:
  fields:

    ####################################################
    # Tab: Main
    ####################################################

    website_name:
      tab: Main
      label: Website Name
      type: text
      default: Cumulus

    website_logo:
      tab: Main
      label: Logo
      type: fileupload

    website_favicon:
      tab: Main
      label: Favicon
      type: fileupload
      default: "/themes/cumulustheme/assets/images/favicon.ico"

    website_author:
      tab: Main
      label: Author
      type: text
      default: InIT.biz

    website_url:
      tab: Main
      label: URL
      type: text
      default: "http://init.biz"

    website_description:
      tab: Main
      label: "Website description"
      type: text

    ####################################################
    # Tab: Colors
    ####################################################

#    primary_color:
#      tab: Colors
#      label: Primary Color
#      type: colorpicker
#      availableColors: ["#f44336","#9c27b0","#2196f3","#cddc39","#ffc107","#607d8b","#808080","#383838","#000000","#ffffff"]
#      default: "#ff5722"
#      assetVar: "lt-primary-color"
#
#    secondary_color:
#      tab: Colors
#      label: Secondary Color
#      type: colorpicker
#      availableColors: ["#f44336","#9c27b0","#2196f3","#cddc39","#ffc107","#607d8b","#808080","#383838","#000000","#ffffff"]
#      default: "#2196f3"
#      assetVar: "lt-secondary-color"
